import os
import json
import chromadb
import re
from typing import Dict, Any, List, TypedDict, Literal
from sentence_transformers import SentenceTransformer
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, END

# Define Agent State Schema
class AgentState(TypedDict):
    user_input: str               # Whisper transcript / child speech
    vision_input: str             # Object labels from camera (e.g. "green leaf")
    current_story: str            # Current active story title
    story_index: int              # Story passage sequence index
    attention_state: str          # focused, distracted, tired, hyper-active, shy_silent
    consecutive_distractions: int # Counter for how many times the child was distracted
    history: List[Dict[str, Any]] # Chat history
    
    # Internal agent recommendations
    recommended_text: str         # The text generated by pedagogical guide
    ui_action: str                # PLAY_TTS, TRIGGER_CAMERA, SHOW_CANVAS, SHOW_CHOICES
    ui_params: Dict[str, Any]     # Parameters for layout (choices, hints, etc.)
    expected_input: str           # speech, image, canvas, touch
    pedagogical_state: str        # storytelling, distraction_recovery, vocabulary_check
    
    # Final output
    final_response_json: Dict[str, Any] # strictly validated JSON response

# Load system instructions
def load_system_instructions():
    filepath = "system_instructions.md"
    if os.path.exists(filepath):
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    return "You are KathaGemma, a patient tutoring voice-first assistant. Output JSON only."

SYSTEM_INSTRUCTIONS = load_system_instructions()

# Initialize ChromaDB client and Embedding model
print("Initializing ChromaDB connection...")
chroma_client = chromadb.PersistentClient(path="./chromadb_store")
try:
    collection = chroma_client.get_collection(name="kathagemma_corpus")
    embed_model = SentenceTransformer("all-MiniLM-L6-v2")
    RAG_AVAILABLE = True
except Exception as e:
    print(f"ChromaDB collection not found: {e}. Running without active RAG.")
    RAG_AVAILABLE = False

# Initialize Gemini Model
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
ACTIVE_MODE = GEMINI_API_KEY is not None

if ACTIVE_MODE:
    print("Gemini API Key detected. Active Mode is enabled.")
    llm = ChatGoogleGenerativeAI(
        model="gemini-1.5-flash",
        google_api_key=GEMINI_API_KEY,
        generation_config={"response_mime_type": "application/json"}
    )
else:
    print("No Gemini API Key detected. Running in Simulation Mode.")
    llm = None

# --- AGENT NODES ---

def sensory_perception_node(state: AgentState) -> Dict[str, Any]:
    """
    EARS & EYES: Converts and normalizes sensory inputs.
    Translates code-switched or regional words into normalized tags.
    """
    user_input = state.get("user_input", "").strip()
    vision_input = state.get("vision_input", "").strip()
    
    # Pre-parse bilingual tokens (Hinglish/Benglish)
    normalized_input = user_input
    
    # Transliteration dictionary map for common local words
    benglish_map = {
        "biral": "cat",
        "lal": "red",
        "gas": "tree",
        "pakhik": "bird",
        "phool": "flower"
    }
    
    for beng, eng in benglish_map.items():
        if beng in normalized_input.lower():
            normalized_input = re.sub(rf"\b{beng}\b", f"{beng} ({eng})", normalized_input, flags=re.IGNORECASE)
            
    print(f"Sensory Interpreter: Input parsed: '{user_input}' -> '{normalized_input}'")
    return {"user_input": normalized_input, "vision_input": vision_input}

def attention_engagement_tracker_node(state: AgentState) -> Dict[str, Any]:
    """
    Tracks child behavior metrics to evaluate focus levels.
    """
    user_input = state.get("user_input", "").lower()
    consec_distractions = state.get("consecutive_distractions", 0)
    
    # Decision tree logic for attention state classification
    if not user_input or "silent" in user_input or "look away" in user_input:
        attention_state = "distracted"
        consec_distractions += 1
    elif "toy car" in user_input or "butterfly" in user_input or "crayon" in user_input:
        attention_state = "distracted"
        consec_distractions += 1
    elif "tired" in user_input or "sleepy" in user_input or "cry" in user_input:
        attention_state = "tired"
        consec_distractions = 0
    else:
        attention_state = "focused"
        consec_distractions = 0
        
    print(f"Attention Tracker: Classification is '{attention_state}' (Distraction count: {consec_distractions})")
    return {
        "attention_state": attention_state,
        "consecutive_distractions": consec_distractions
    }

def storytelling_branch_node(state: AgentState) -> Dict[str, Any]:
    """
    Pedagogical storytelling branch using ChromaDB RAG.
    """
    story_index = state.get("story_index", 0)
    user_input = state.get("user_input", "")
    
    context = ""
    source_info = "Local Database"
    
    if RAG_AVAILABLE:
        try:
            query_embedding = embed_model.encode([user_input or "story"]).tolist()
            results = collection.query(
                query_embeddings=query_embedding,
                n_results=1
            )
            if results and results["documents"] and results["documents"][0]:
                context = results["documents"][0][0]
                meta = results["metadatas"][0][0]
                source_info = f"{meta.get('source', 'RAG')} - {meta.get('book_title', 'Story')}"
                print(f"RAG Retrieval: Grounded in '{source_info}'")
        except Exception as e:
            print(f"RAG query error: {e}")
            
    if not context:
        default_stories = [
            "Raju lived near the big green forest. Every morning, he walked to the pond.",
            "One sunny day, Raju heard a sound. Splash! Splash! A small elephant was playing in the water.",
            "Suddenly, dark clouds came. Boom! It started to rain heavily. Raju had no umbrella.",
            "The elephant plucked a giant green leaf from a banana tree and held it over Raju's head like an umbrella."
        ]
        context = default_stories[story_index % len(default_stories)]
        source_info = "Fallback default story"
        
    recommended_text = f"And look what happens next! {context} Raju was so excited! Can you tell me what you see?"
    
    return {
        "recommended_text": recommended_text,
        "ui_action": "PLAY_TTS",
        "ui_params": {"source": source_info},
        "expected_input": "speech",
        "pedagogical_state": "storytelling",
        "story_index": story_index + 1
    }

def active_recovery_quest_node(state: AgentState) -> Dict[str, Any]:
    """
    Engages distracted child with physical interactive quests.
    """
    consec_distractions = state.get("consecutive_distractions", 1)
    
    if consec_distractions % 2 == 1:
        recommended_text = "Hey Aarav! Raju needs a big green leaf to protect himself from the rain. Find something green in your room and show it to my camera!"
        ui_action = "TRIGGER_CAMERA"
        ui_params = {"target_prompt": "Find something green"}
        expected_input = "image"
    else:
        recommended_text = "Wow! You love drawing, don't you? Let's draw a road for Raju's car on the screen with your finger!"
        ui_action = "SHOW_CANVAS"
        ui_params = {"target_prompt": "Draw a road for Raju"}
        expected_input = "canvas"
        
    return {
        "recommended_text": recommended_text,
        "ui_action": ui_action,
        "ui_params": ui_params,
        "expected_input": expected_input,
        "pedagogical_state": "distraction_recovery"
    }

def calming_branch_node(state: AgentState) -> Dict[str, Any]:
    """
    Soft recovery branch for tired or overstimulated child.
    """
    recommended_text = "Oh, are you feeling tired? Let's take a deep breath together. Sshhh... Would you like to listen to a sweet lullaby or do a small puzzle?"
    return {
        "recommended_text": recommended_text,
        "ui_action": "SHOW_CHOICES",
        "ui_params": {
            "choices": ["Listen to Lullaby", "Do a simple puzzle"]
        },
        "expected_input": "touch",
        "pedagogical_state": "distraction_recovery"
    }

def json_state_orchestrator_node(state: AgentState) -> Dict[str, Any]:
    """
    Aggregates all results, formats system context and constraints,
    and runs Gemma (Gemini) API to output strictly validated JSON frames.
    """
    recommended_text = state.get("recommended_text", "")
    ui_action = state.get("ui_action", "PLAY_TTS")
    ui_params = state.get("ui_params", {})
    expected_input = state.get("expected_input", "speech")
    pedagogical_state = state.get("pedagogical_state", "storytelling")
    
    final_json = None
    
    if ACTIVE_MODE and llm:
        prompt = f"""
        Generate a structured JSON output representing the current tutoring state.
        
        Recommended Narrative Text: "{recommended_text}"
        UI Action Layout: "{ui_action}"
        UI Parameters: {json.dumps(ui_params)}
        Expected Next Input: "{expected_input}"
        Pedagogical State: "{pedagogical_state}"
        
        Format strictly as JSON. No markdown code blocks, prefixes, or suffixes.
        """
        try:
            response = llm.invoke([
                SystemMessage(content=SYSTEM_INSTRUCTIONS),
                HumanMessage(content=prompt)
            ])
            raw_text = response.content.strip()
            if raw_text.startswith("```json"):
                raw_text = raw_text.split("```json")[1].split("```")[0].strip()
            elif raw_text.startswith("```"):
                raw_text = raw_text.split("```")[1].split("```")[0].strip()
                
            final_json = json.loads(raw_text)
        except Exception as e:
            print(f"JSON Orchestrator Gemini prompt failed: {e}. Falling back to default formatter.")
            
    if not final_json:
        final_json = {
            "spoken_text": recommended_text,
            "ui_action": ui_action,
            "ui_params": ui_params,
            "pedagogical_state": pedagogical_state,
            "expected_input": expected_input
        }
        
    required_keys = ["spoken_text", "ui_action", "ui_params", "pedagogical_state", "expected_input"]
    for key in required_keys:
        if key not in final_json:
            if key == "spoken_text":
                final_json["spoken_text"] = recommended_text
            elif key == "ui_action":
                final_json["ui_action"] = ui_action
            elif key == "ui_params":
                final_json["ui_params"] = ui_params
            elif key == "pedagogical_state":
                final_json["pedagogical_state"] = pedagogical_state
            elif key == "expected_input":
                final_json["expected_input"] = expected_input

    print(f"JSON Orchestrator: Validated JSON output successfully generated.")
    return {"final_response_json": final_json}

def route_attention_state(state: AgentState) -> str:
    att = state.get("attention_state", "focused")
    if att == "distracted":
        return "active_recovery"
    elif att == "tired":
        return "calming"
    else:
        return "storytelling"

def build_agent_graph():
    workflow = StateGraph(AgentState)
    workflow.add_node("sensory_interpreter", sensory_perception_node)
    workflow.add_node("attention_tracker", attention_engagement_tracker_node)
    workflow.add_node("storytelling", storytelling_branch_node)
    workflow.add_node("active_recovery", active_recovery_quest_node)
    workflow.add_node("calming", calming_branch_node)
    workflow.add_node("json_orchestrator", json_state_orchestrator_node)
    
    workflow.set_entry_point("sensory_interpreter")
    workflow.add_edge("sensory_interpreter", "attention_tracker")
    
    workflow.add_conditional_edges(
        "attention_tracker",
        route_attention_state,
        {
            "storytelling": "storytelling",
            "active_recovery": "active_recovery",
            "calming": "calming"
        }
    )
    
    workflow.add_edge("storytelling", "json_orchestrator")
    workflow.add_edge("active_recovery", "json_orchestrator")
    workflow.add_edge("calming", "json_orchestrator")
    workflow.add_edge("json_orchestrator", END)
    return workflow.compile()

agent_app = build_agent_graph()

def run_agent_loop(user_input: str, vision_input: str = "", current_state: Dict[str, Any] = None) -> Dict[str, Any]:
    if current_state is None:
        current_state = {
            "story_index": 0,
            "current_story": "Mithai",
            "consecutive_distractions": 0,
            "history": []
        }
        
    inputs = {
        "user_input": user_input,
        "vision_input": vision_input,
        "current_story": current_state.get("current_story", "Mithai"),
        "story_index": current_state.get("story_index", 0),
        "consecutive_distractions": current_state.get("consecutive_distractions", 0),
        "history": current_state.get("history", [])
    }
    
    result = agent_app.invoke(inputs)
    updated_state = {
        "current_story": result.get("current_story"),
        "story_index": result.get("story_index"),
        "consecutive_distractions": result.get("consecutive_distractions"),
        "history": result.get("history") + [{"user": user_input, "system": result.get("final_response_json")}]
    }
    
    return {
        "state": updated_state,
        "response": result.get("final_response_json")
    }

if __name__ == "__main__":
    print("\n--- Running Orchestrator Self-Test (Focused Child) ---")
    res1 = run_agent_loop("I see the little parrot sitting on the tree branch.")
    print(json.dumps(res1["response"], indent=2))
